// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPGMNJ6QcjVCWklNITR56J2rKcwg8xzyE',
    appId: '1:947020594115:android:c691bb3138303125419b76',
    messagingSenderId: '947020594115',
    projectId: 'ecommerceapp-9bbed',
    storageBucket: 'ecommerceapp-9bbed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJmJCpcYfB-YiPdyA-pcRPsVeYMZyzk4Y',
    appId: '1:947020594115:ios:f3c8285817abe017419b76',
    messagingSenderId: '947020594115',
    projectId: 'ecommerceapp-9bbed',
    storageBucket: 'ecommerceapp-9bbed.appspot.com',
    androidClientId: '947020594115-426l2tc0r5s4v8ioqjh7g27t6i5m945s.apps.googleusercontent.com',
    iosClientId: '947020594115-kui24ap1krjnkd4gv3p196u7i45q6jmq.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBr9zi2d8TUUL16CVPiQPThdp2O6PB-dCY',
    appId: '1:947020594115:web:a73255ee008b04d9419b76',
    messagingSenderId: '947020594115',
    projectId: 'ecommerceapp-9bbed',
    authDomain: 'ecommerceapp-9bbed.firebaseapp.com',
    storageBucket: 'ecommerceapp-9bbed.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJmJCpcYfB-YiPdyA-pcRPsVeYMZyzk4Y',
    appId: '1:947020594115:ios:f3c8285817abe017419b76',
    messagingSenderId: '947020594115',
    projectId: 'ecommerceapp-9bbed',
    storageBucket: 'ecommerceapp-9bbed.appspot.com',
    androidClientId: '947020594115-426l2tc0r5s4v8ioqjh7g27t6i5m945s.apps.googleusercontent.com',
    iosClientId: '947020594115-kui24ap1krjnkd4gv3p196u7i45q6jmq.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBr9zi2d8TUUL16CVPiQPThdp2O6PB-dCY',
    appId: '1:947020594115:web:fbd96ddb4ba83dbf419b76',
    messagingSenderId: '947020594115',
    projectId: 'ecommerceapp-9bbed',
    authDomain: 'ecommerceapp-9bbed.firebaseapp.com',
    storageBucket: 'ecommerceapp-9bbed.appspot.com',
  );

}